### ISSUE TITLE
Did you publish a paper on this?

### ISSUE THREAD

**Issue by GoingMyWay** [rhaps0dy/malmo-challenge#1]
Hi, you won the challenge and did you write a paper on how you achieved this challenge?

**Comment by rhaps0dy** [comment]
Hello! For the entry we wrote a description of our approach, which is [in the GitHub repository](https://github.com/rhaps0dy/malmo-challenge/blob/master/SUBMISSION_ENTRY_DESCRIPTION.md). There is also a video linked from it and some spoken explanation. I also made a short [slide deck](https://www.dropbox.com/s/mm1vf1k4vjyuf7r/Balancing%20Cooperation%20and%20Defection%20in%20a%202-agent%20grid-world%20game.pdf?dl=0) for a 5 or 10 minute talk.

Does that help?

**Comment by GoingMyWay** [comment]
@rhaps0dy  it helps, thank you!
